# Generated by Django 4.0.5 on 2022-07-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('uuid', models.UUIDField()),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'installations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('uuid', models.UUIDField()),
                ('max_players', models.IntegerField()),
                ('num_players', models.IntegerField()),
                ('human_won', models.BooleanField()),
                ('version', models.CharField(max_length=50)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdparchis.installation')),
            ],
            options={
                'db_table': 'games',
                'managed': True,
            },
        ),
    ]
