# Generated by Django 5.0.6 on 2024-05-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdparchis", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Game",
            new_name="GameStatistic",
        ),
        migrations.RenameModel(
            old_name="Installation",
            new_name="InstallationStatistic",
        ),
        migrations.AlterModelTable(
            name="gamestatistic",
            table="games_statistics",
        ),
        migrations.AlterModelTable(
            name="installationstatistic",
            table="installations_statistics",
        ),
    ]
