# Generated by Django 5.0.6 on 2024-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdparchis", "0004_game_datetime_game_max_players_game_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamestatistic",
            name="uuid",
            field=models.UUIDField(blank=True),
        ),
    ]
