# Generated by Django 5.0.6 on 2024-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdparchis", "0005_alter_gamestatistic_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="datetime",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="uuid",
            field=models.UUIDField(blank=True),
        ),
    ]
